name: Hexo Auto-Deploy to Github
on:
  push:
    branches:
      - gitee
jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v1

      - name: 2. setup nodejs...
        uses: actions/setup-node@v1

      - name: 3. install hexo...
        run: |
          npm install hexo-cli -g
          npm install
      - name: 4. hexo generate public files...
        run: |
          hexo clean
          hexo g
      - name: 5. deploy 'public files' to 'gitee.com/hexoblog' repo
          env:
            GT_REF: https://947124233:${{secrets.GT_Token}}@gitee.com/947124233/hexoblog.git
          run: |
            hexo g
            git clone ${GT_REF} gt-public
            cp -rf public/* gt-public/
            cd gt-public/
            git add .
            git commit -am "Deployed to Gitee by Github Actions"
            git push
