name: Hexo Auto-Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v1

      - name: 2. setup enviorment...
        uses: actions/setup-node@v1
        run: |
          npm install hexo-cli -g
          npm install
      - name: 5. deploy 'public files' to 'github.io' repo...
        env:
          GH_REF: https://a347807131:${{ secrets.GH_Token }}@github.com/a347807131/a347807131.github.io.git
        run: |
          git config --global user.name "civin"
          git config --global user.email "civin@bupt.edu.cn"
          git clone ${GH_REF} public
          hexo g
          cd public
          git add .
          git commit -am "Deployed to Github by GitHub Actions ..."
          git push origin master